#TTL
security.jwt.access.timeout=300
#minute
security.jwt.refresh.timeout=30
#day
security.jwt.reset.timeout=15
#minute
# jwt secret key
security.jwt.access.secretKey=${ACCESS_SECRET}
security.jwt.refresh.secretKey=${REFRESH_SECRET}
security.jwt.reset.secretKey=${RESET_SECRET}
# database
spring.datasource.url=${DB_RAILWAY_URL}
spring.datasource.username=${DB_RAILWAY_USERNAME}
spring.datasource.password=${DB_RAILWAY_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# init data setup
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data-${spring.profiles.active}.sql
#spring.jpa.defer-datasource-initialization=true
# web push api key
vapid.public.key=${VAPID_PUBLIC_KEY}
vapid.private.key=${VAPID_PRIVATE_KEY}
vapid.subject=${VAPID_SUBJECT}
#AI env
gemini.api-key=${GEMINI_API_KEY}
#Frontend port
front-end.port=${http://localhost:3000}
#deploy
server.port: ${PORT:8080}