#TTL
security.jwt.access.timeout=15
#minute
security.jwt.refresh.timeout=30
#day
security.jwt.reset.timeout=15
#minute
#secret key
security.jwt.access.secretKey={ACCESS_SECRET}
security.jwt.refresh.secretKey={REFRESH_SECRET}
security.jwt.reset.secretKey={RESET_SECRET}
# database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

