#TTL
security.jwt.access.timeout=15 #minute
security.jwt.refresh.timeout=30 #day
security.jwt.reset.timeout=15 #minute
#secret key
security.jwt.access.secretKey={security.jwt.access.secretKey}
security.jwt.refresh.secretKey={security.jwt.refresh.secretKey}
security.jwt.reset.secretKey={security.jwt.reset.secretKey}
# database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

